name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build ./go-back --file ./go-back/Dockerfile

      - name: Setup Go environment
        uses: actions/setup-go@v7
        with:
          go-version-file: go-back/go.mod
